version: '3.8'
services:
  sciencehub-backend:
    image: tudoraorban/sciencehub-backend:latest
    ports:
      - "5183:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
