version: '3.8'

services:
  backend:
    image: sciencehub-backend:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    
  frontend:
    image: sciencehub-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - backend